version: '3.6'
services:
  web:
    container_name: uboot
    image: 'mengplus/uboot:latest'
    restart: always
    tty: true     # 给容器设置一个伪终端防止进程结束容器退出
    hostname: 'docker'
    #environment: # 添加环境变量。
     # GITLAB_OMNIBUS_CONFIG: |
     #   external_url 'https://gitlab.example.com'
     #   # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - '../:/home/uboot/workspace'
    shm_size: '256m'
  # cap_add:
  #  - ALL # 开启全部权限
  #devices:  #挂设备
  # - "/dev/ttyUSB0:/dev/ttyUSB0"

